### ISSUE TITLE
Modify Client Table and Client's add and edit function

### ISSUE THREAD

**Issue by aung-zan** [aung-zan/Hospital-Reservation#4]
### Description
Add the phone_number field in client table and modify the client's add and edit functions and view.

### Tasks
- [ ] Create Update migration file for client table.
- [ ] Modify client's add function and view.
- [ ] Modify client's edit function and view.
